const sidebar=document.getElementById('sidebar');const menuBtn=document.getElementById('menuBtn');const overlay=document.getElementById('overlay');
function setSidebar(open){sidebar?.classList.toggle('open',open);overlay?.classList.toggle('show',open);document.body.style.overflow=open?'hidden':''}menuBtn?.addEventListener('click',()=>setSidebar(true));overlay?.addEventListener('click',()=>setSidebar(false));window.addEventListener('resize',()=>{if(window.innerWidth>900)setSidebar(false)});

const SUPABASE_URL='https://bxnfzuglfwytiyaguwjj.supabase.co';
const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4bmZ6dWdsZnd5dGl5YWd1d2pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyMjk0NjUsImV4cCI6MjA4NDgwNTQ2NX0.IcmVvbboKLkJLkE31_udEtvhPl66-kmZAvmPCT_lk5o';
const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const state={session:null,kid:null,unitProgress:[],tasks:[],subjects:[]};
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

const css=document.createElement('style');css.textContent=`
.learning-modes{margin:18px 0 16px;padding:20px;background:linear-gradient(135deg,#fff,#f6fdff 58%,#eefafb);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow)}
.learning-modes-head{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin-bottom:15px}.learning-modes-head h2{margin:0;font-size:22px}.learning-modes-head p{margin:5px 0 0;color:var(--muted);font-size:13px}.learning-modes-badge{padding:7px 10px;border-radius:999px;background:#e8fafc;color:#078fa1;font-size:11px;font-weight:800;white-space:nowrap}.learning-mode-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.learning-mode-card{position:relative;min-height:132px;border:1px solid var(--line);border-radius:18px;padding:16px;display:flex;flex-direction:column;align-items:flex-start;text-align:right;background:#fff;color:var(--text);transition:.18s}.learning-mode-card:hover{transform:translateY(-2px);box-shadow:0 13px 28px rgba(35,91,110,.10);border-color:#bfe6ec}.learning-mode-card.learn{background:linear-gradient(145deg,#f5fdff,#e7f8ff)}.learning-mode-card.practice{background:linear-gradient(145deg,#fffcf8,#fff1e7)}.learning-mode-card.games{background:linear-gradient(145deg,#fbf9ff,#f0ecff)}.learning-mode-card.homework{background:linear-gradient(145deg,#f8fffc,#e8faf4)}.learning-mode-icon{width:46px;height:46px;display:grid;place-items:center;border-radius:14px;background:rgba(255,255,255,.86);font-size:23px;margin-bottom:11px}.learning-mode-card strong{font-size:16px;margin-bottom:3px}.learning-mode-card small{font-size:11px;color:#6d8998;line-height:1.45}.learning-mode-arrow{position:absolute;left:14px;top:14px;width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:#fff;color:#128fa2;font-weight:800}.learning-paths{margin-top:13px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.learning-path{display:flex;align-items:center;justify-content:space-between;gap:12px;border:1px solid var(--line);border-radius:14px;padding:12px 14px;background:rgba(255,255,255,.8)}.learning-path-main{display:flex;align-items:center;gap:10px}.learning-path-icon{width:38px;height:38px;display:grid;place-items:center;border-radius:11px;background:#edf9fb}.learning-path strong{display:block;font-size:13px}.learning-path small{display:block;color:var(--muted);font-size:10px}.learning-path button{border:0;background:transparent;color:#0b93a5;font-weight:800}.connect-banner{margin-bottom:14px;padding:12px 14px;border:1px solid #bfe8ee;background:#effbfc;border-radius:14px;color:#276476;font-size:13px}.connect-banner.warn{border-color:#f3d4a4;background:#fff8ed;color:#825b24}.empty-live{padding:20px;text-align:center;color:#7894a2}.mode-toast{position:fixed;left:24px;bottom:24px;z-index:60;padding:12px 15px;border-radius:13px;background:#16384a;color:white;opacity:0;transform:translateY(12px);pointer-events:none;transition:.2s}.mode-toast.show{opacity:1;transform:translateY(0)}
@media(max-width:1180px){.learning-mode-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:700px){.learning-modes{padding:15px}.learning-modes-head{align-items:flex-start;flex-direction:column;gap:7px}.learning-mode-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.learning-mode-card{min-height:122px;padding:13px}.learning-paths{grid-template-columns:1fr}}@media(max-width:390px){.learning-mode-grid{grid-template-columns:1fr}}`;document.head.appendChild(css);

const statsGrid=document.querySelector('.stats-grid');if(statsGrid&&!document.querySelector('.learning-modes')){const section=document.createElement('section');section.className='learning-modes';section.innerHTML=`<div class="learning-modes-head"><div><p class="eyebrow">המורה AI שלך</p><h2>איך בא לך ללמוד עכשיו?</h2><p>בחר דרך ללמוד — המורה תתאים את השיחה והפעילות למה שבחרת.</p></div><span class="learning-modes-badge">✨ הכל מתחבר לאותו AI</span></div><div class="learning-mode-grid"><button class="learning-mode-card learn" data-mode="learn"><span class="learning-mode-arrow">←</span><span class="learning-mode-icon">👩🏻‍🏫</span><strong>למד אותי משהו</strong><small>שאל על כל נושא והמורה תלמד אותך שלב אחרי שלב.</small></button><button class="learning-mode-card practice" data-mode="practice"><span class="learning-mode-arrow">←</span><span class="learning-mode-icon">✏️</span><strong>תרגול</strong><small>תרגול חכם לפי המקצוע, הנושא והרמה שלך.</small></button><button class="learning-mode-card games" data-mode="games"><span class="learning-mode-arrow">←</span><span class="learning-mode-icon">🎮</span><strong>משחקי למידה</strong><small>משחקים קצרים שעוזרים לחזור על החומר.</small></button><button class="learning-mode-card homework" data-mode="homework"><span class="learning-mode-arrow">←</span><span class="learning-mode-icon">📸</span><strong>שיעורי בית</strong><small>מעלים צילום או קובץ והמורה עוזרת להבין ולפתור.</small></button></div><div class="learning-paths"><div class="learning-path"><div class="learning-path-main"><span class="learning-path-icon">📚</span><div><strong>תכנית הלימודים שלי</strong><small>המקצועות והשיעורים המובנים של IAKIDS</small></div></div><button data-mode="curriculum">לצפייה ←</button></div><div class="learning-path"><div class="learning-path-main"><span class="learning-path-icon">✨</span><div><strong>מה שבחרתי ללמוד</strong><small>מקצועות ונושאים שהוספת בעצמך</small></div></div><button data-mode="personal">לצפייה ←</button></div></div>`;statsGrid.insertAdjacentElement('afterend',section)}

const nav=document.querySelector('.nav');if(nav){const practice=[...nav.querySelectorAll('.nav-item')].find(x=>x.textContent.includes('תרגול'));if(practice&&!nav.querySelector('[data-v2-nav="games"]'))practice.insertAdjacentHTML('afterend','<a class="nav-item" data-v2-nav="games" href="#"><span>🎮</span><span>משחקי למידה</span></a>');const files=[...nav.querySelectorAll('.nav-item')].find(x=>x.textContent.includes('הקבצים שלי'));if(files&&!nav.querySelector('[data-v2-nav="personal"]'))files.insertAdjacentHTML('afterend','<a class="nav-item" data-v2-nav="personal" href="#"><span>✨</span><span>מה שבחרתי ללמוד</span></a>')}

const toast=document.createElement('div');toast.className='mode-toast';document.body.appendChild(toast);let toastTimer;function showToast(t){toast.textContent=t;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2200)}
document.addEventListener('click',e=>{const mode=e.target.closest('[data-mode]')?.dataset.mode;if(mode==='homework'){location.href='./homework.html';return}if(mode){showToast('המסך הזה יחובר בהמשך לאותו מנוע.');return}const navItem=e.target.closest('.nav-item,.mobile-nav a');if(navItem){if(navItem.getAttribute('href')==='#')e.preventDefault();setSidebar(false)}});

function gradeLabel(n){const map={1:'א׳',2:'ב׳',3:'ג׳',4:'ד׳',5:'ה׳',6:'ו׳',7:'ז׳',8:'ח׳',9:'ט׳'};return map[Number(n)]||String(n||'')}
function statusText(status){if(status==='completed')return['הושלם','done'];if(status==='in_progress'||status==='partial')return['בביצוע','running'];return['לא התחיל','new']}
function subjectIcon(s){if(/מתמט/.test(s))return'🧮';if(/עברית/.test(s))return'📘';if(/אנגל/.test(s))return'🔤';if(/מדע/.test(s))return'🧪';if(/תנ/.test(s))return'📜';return'📚'}
function pct(v){const n=Number(v||0);return Math.max(0,Math.min(100,Math.round(n)))}
function setBanner(text,warn=false){const el=$('connectionBanner');if(!el)return;el.hidden=false;el.className='connect-banner'+(warn?' warn':'');el.textContent=text}

async function getSession(){if(!sb)return null;const {data,error}=await sb.auth.getSession();if(error)throw error;state.session=data?.session||null;return state.session}
async function getKid(){const s=state.session;if(!s)return null;let kidId=localStorage.getItem('active_kid_id');if(!kidId){const {data,error}=await sb.from('kids_profiles').select('id').eq('user_id',s.user.id).order('created_at',{ascending:true}).limit(1);if(error)throw error;kidId=data?.[0]?.id||null;if(kidId)localStorage.setItem('active_kid_id',kidId)}if(!kidId)return null;const {data,error}=await sb.from('kids_profiles').select('id,user_id,child_name,age,avatar_key,coins,diamonds').eq('id',kidId).eq('user_id',s.user.id).single();if(error)throw error;state.kid=data;return data}
async function loadDashboardData(){const kid=state.kid;if(!kid)return;const kidId=kid.id;const now=new Date().toISOString();const [unitRes,taskRes,subjectRes]=await Promise.all([sb.from('kid_unit_lesson_progress').select('unit_lesson_id,learning_lesson_id,status,progress_percent,mastery_score,last_activity_at').eq('kid_id',kidId).order('last_activity_at',{ascending:false}),sb.from('kid_tasks').select('id,task_type,title,subject,topic,due_at,status,priority').eq('kid_id',kidId).eq('status','pending').order('due_at',{ascending:true}),sb.from('kid_custom_subjects').select('id,subject_name,status,created_at').eq('kid_id',kidId).neq('status','archived').order('updated_at',{ascending:false})]);if(unitRes.error)throw unitRes.error;if(taskRes.error)throw taskRes.error;if(subjectRes.error)throw subjectRes.error;state.unitProgress=unitRes.data||[];state.tasks=taskRes.data||[];state.subjects=subjectRes.data||[];
  const lessonIds=[...new Set(state.unitProgress.map(r=>r.learning_lesson_id).filter(Boolean))];const unitIds=[...new Set(state.unitProgress.map(r=>r.unit_lesson_id).filter(Boolean))];let lessons=[],units=[];if(lessonIds.length){const r=await sb.from('learning_lessons').select('id,subject,category,lesson_name,grade').in('id',lessonIds);if(!r.error)lessons=r.data||[]}if(unitIds.length){const r=await sb.from('lesson_units_content').select('id,learning_lesson_id,lesson_name,lesson_order,unit_name').in('id',unitIds);if(!r.error)units=r.data||[]}renderLive(kid,lessons,units,now)}

function renderLive(kid,lessons,units,nowIso){const name=kid.child_name||'הילד/ה';$('kidName').textContent=name;$('kidGrade').textContent=`כיתה ${gradeLabel(kid.age)}`;$('kidAvatar').textContent=name.trim().charAt(0)||'י';$('starsCount').textContent=Number(kid.coins||0);$('diamondsCount').textContent=Number(kid.diamonds||0);$('heroGreeting').textContent=`שלום ${name}! 👋`;$('heroSub').textContent='כיף לראות אותך שוב. המשך בדיוק מהמקום שבו עצרת.';$('aiGreeting').textContent=`שלום ${name}!`;
 const active=state.unitProgress.filter(r=>r.status==='in_progress'||r.status==='partial');const avg=state.unitProgress.length?Math.round(state.unitProgress.reduce((a,r)=>a+pct(r.progress_percent),0)/state.unitProgress.length):0;const exams=state.tasks.filter(t=>t.task_type==='exam'&&(!t.due_at||t.due_at>=nowIso));$('activeLessonsStat').textContent=active.length;$('openTasksStat').textContent=state.tasks.length;$('progressStat').textContent=`${avg}%`;$('upcomingExamsStat').textContent=exams.length;$('bottomProgress').textContent=`${avg}%`;$('bottomProgressCopy').textContent=state.unitProgress.length?`${state.unitProgress.length} שיעורים עם נתוני התקדמות`:'עדיין אין נתוני התקדמות';$('sidebarProgress').style.width=`${avg}%`;$('weeklyGoalCopy').textContent=avg>=80?'עמדת ביעד הלמידה שלך':'המשך ללמוד כדי להתקדם';
 const lessonMap=new Map(lessons.map(x=>[Number(x.id),x]));const unitMap=new Map(units.map(x=>[Number(x.id),x]));const rows=(active.length?active:state.unitProgress).slice(0,4);$('lessonRows').innerHTML=rows.length?rows.map(r=>{const l=lessonMap.get(Number(r.learning_lesson_id))||{};const u=unitMap.get(Number(r.unit_lesson_id))||{};const [st,cl]=statusText(r.status);const p=pct(r.progress_percent);return `<tr><td><div class="subject"><span class="subject-icon blue-bg">${subjectIcon(l.subject||'')}</span><div><strong>${esc(l.subject||'לימוד')}</strong><small>${esc(l.category||u.unit_name||'')}</small></div></div></td><td><strong>${esc(u.lesson_name||l.lesson_name||'השיעור הבא')}</strong><small>${u.lesson_order?`שיעור ${u.lesson_order}`:''}</small></td><td><span class="status ${cl}">${st}</span></td><td><div class="progress-cell"><strong>${p}%</strong><div class="progress"><span style="width:${p}%"></span></div></div></td><td><button class="table-action" data-live-lesson="${r.learning_lesson_id||''}">המשך שיעור ▶</button></td></tr>`}).join(''):'<tr><td colspan="5" class="empty-live">עדיין אין שיעורים שהתחלת. אפשר לבחור מקצוע ולהתחיל ללמוד.</td></tr>';
 $('nearTasks').innerHTML=state.tasks.length?state.tasks.slice(0,3).map(t=>`<div class="task"><div><strong>${esc(t.title)}</strong><small>${esc([t.subject,t.topic].filter(Boolean).join(' · '))}</small></div><span class="task-date${t.priority>=2?' urgent':''}">${t.due_at?new Date(t.due_at).toLocaleDateString('he-IL',{day:'numeric',month:'numeric'}):'ללא תאריך'}</span></div>`).join(''):'<div class="empty-live">אין כרגע משימות פתוחות.</div>';
 $('personalSubjects').innerHTML=state.subjects.length?state.subjects.slice(0,3).map(s=>`<div class="achievement"><span class="medal blue-medal">✨</span><div><strong>${esc(s.subject_name)}</strong><small>${s.status==='active'?'פעיל':'בתהליך בנייה'}</small></div></div>`).join(''):'<div class="empty-live">עדיין לא הוספת נושא אישי.</div>';setBanner(`מחובר לנתונים האמיתיים של ${name}.`,false)}

async function initLive(){try{const session=await getSession();if(!session){const onPreview=location.hostname.includes('onrender.com')&&location.hostname.includes('iakids-v2');setBanner(onPreview?'זהו Preview ללא ההתחברות של iakids.app. לפתיחת הנתונים האמיתיים עברו ל־iakids.app/frontend-v2/':'אין Session פעיל. התחברו מחדש לחשבון.',true);$('kidName').textContent='הילד/ה שלי';$('heroSub').textContent='יש להתחבר כדי לטעון נתונים אמיתיים.';return}const kid=await getKid();if(!kid){setBanner('לא נמצא פרופיל ילד בחשבון.',true);return}await loadDashboardData()}catch(err){console.error('V2 dashboard init failed',err);setBanner('לא הצלחתי לטעון את נתוני הדשבורד. המערכת הישנה לא נפגעה.',true)}}

document.addEventListener('click',e=>{const lesson=e.target.closest('[data-live-lesson]');if(lesson){const id=lesson.dataset.liveLesson;if(id)location.href=`/he/workspace/?lesson_id=${encodeURIComponent(id)}`}});
initLive();
