const state={step:1,file:null,fileUrl:null,child:null};
const $=(id)=>document.getElementById(id);
const els={fileInput:$('fileInput'),cameraInput:$('cameraInput'),dropZone:$('dropZone'),uploadState:$('uploadState'),imagePreview:$('imagePreview'),pdfPreview:$('pdfPreview'),genericPreview:$('genericPreview'),fileName:$('fileName'),replaceFileBtn:$('replaceFileBtn'),analyzeBtn:$('analyzeBtn'),sourceStatus:$('sourceStatus'),notebook:$('homeworkNotebook'),notebookStatus:$('notebookStatus'),notebookCount:$('notebookCount'),steps:[...document.querySelectorAll('#steps li')],mobileStepNumber:$('mobileStepNumber'),mobileProgressBar:$('mobileProgressBar'),flowFill:$('flowFill'),flowSteps:[...document.querySelectorAll('#flowSteps>div')],chat:$('chat'),chatForm:$('chatForm'),chatInput:$('chatInput'),quickActions:$('quickActions'),tutorPanel:$('tutorPanel'),floatingChat:$('floatingChat'),closeChat:$('closeChat'),chatOverlay:$('chatOverlay'),audioPlay:$('audioPlay'),audioStatus:$('audioStatus'),understandingText:$('understandingText'),childName:$('childName'),childGrade:$('childGrade'),childAvatar:$('childAvatar')};
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function setStep(step){state.step=Math.max(1,Math.min(5,step));els.steps.forEach(item=>{const n=+item.dataset.step;item.classList.toggle('active',n===state.step);item.classList.toggle('done',n<state.step)});if(els.mobileStepNumber)els.mobileStepNumber.textContent=state.step;if(els.mobileProgressBar)els.mobileProgressBar.style.width=`${state.step*20}%`;if(els.flowFill)els.flowFill.style.width=`${(state.step-1)*25}%`;els.flowSteps.forEach((item,i)=>item.classList.toggle('active',i<=state.step-1));}
function addMessage(role,text){const box=document.createElement('div');box.className=`message ${role}`;box.innerHTML=`<p>${escapeHtml(text)}</p>`;els.chat.appendChild(box);els.chat.scrollTop=els.chat.scrollHeight;}
function clearPreview(){[els.imagePreview,els.pdfPreview,els.genericPreview].forEach(el=>el?.classList.add('hidden'));if(state.fileUrl){URL.revokeObjectURL(state.fileUrl);state.fileUrl=null;}els.imagePreview?.removeAttribute('src');els.pdfPreview?.removeAttribute('src');}
function showFile(file){if(!file)return;state.file=file;clearPreview();state.fileUrl=URL.createObjectURL(file);els.uploadState.classList.add('hidden');els.fileName.textContent=file.name||'שיעורי בית';els.replaceFileBtn.classList.remove('hidden');els.analyzeBtn.disabled=false;if(file.type?.startsWith('image/')){els.imagePreview.src=state.fileUrl;els.imagePreview.classList.remove('hidden');}else if(file.type==='application/pdf'||file.name?.toLowerCase().endsWith('.pdf')){els.pdfPreview.src=state.fileUrl;els.pdfPreview.classList.remove('hidden');}else{els.genericPreview.classList.remove('hidden');}els.sourceStatus.textContent='הקובץ הועלה. אפשר להמשיך לזיהוי המקצוע והנושא.';setStep(2);addMessage('teacher','קיבלתי את הקובץ. מנוע הזיהוי הקיים עדיין לא מחובר ל־V2, ולכן אני לא אנחש מה יש בו.');}
[els.fileInput,els.cameraInput].forEach(input=>input?.addEventListener('change',()=>showFile(input.files?.[0])));
['dragenter','dragover'].forEach(name=>els.dropZone?.addEventListener(name,e=>{e.preventDefault();els.dropZone.classList.add('dragover')}));
['dragleave','drop'].forEach(name=>els.dropZone?.addEventListener(name,e=>{e.preventDefault();els.dropZone.classList.remove('dragover')}));
els.dropZone?.addEventListener('drop',e=>showFile(e.dataTransfer.files?.[0]));
els.replaceFileBtn?.addEventListener('click',()=>els.fileInput.click());
els.analyzeBtn?.addEventListener('click',()=>{if(!state.file)return;els.sourceStatus.textContent='מוכן לחיבור למנוע שיעורי הבית הקיים: Vision → מקצוע → נושא → שאלות.';addMessage('teacher','הקובץ מוכן לניתוח. בחיבור הבא אשתמש בתוצאות האמיתיות של מנוע שיעורי הבית הקיים ואציג כאן את המקצוע, הנושא והשאלה.');setStep(2);});
const NOTE_KEY='iakids-v2-homework-notebook';
try{const saved=localStorage.getItem(NOTE_KEY);if(saved)els.notebook.innerHTML=saved;}catch{}
function saveNotebook(){const text=els.notebook.innerText.trim();try{localStorage.setItem(NOTE_KEY,els.notebook.innerHTML)}catch{}els.notebookStatus.textContent='נשמר אוטומטית';els.notebookCount.textContent=`${text.length} תווים`;if(text.length>0&&state.step<4)setStep(4);}
els.notebook?.addEventListener('input',()=>{els.notebookStatus.textContent='שומר...';clearTimeout(saveNotebook.t);saveNotebook.t=setTimeout(saveNotebook,250)});saveNotebook();
function openChat(){els.tutorPanel.classList.add('open');els.chatOverlay.classList.add('show');}
function closeChat(){els.tutorPanel.classList.remove('open');els.chatOverlay.classList.remove('show');}
els.floatingChat?.addEventListener('click',openChat);els.closeChat?.addEventListener('click',closeChat);els.chatOverlay?.addEventListener('click',closeChat);
function submitMessage(text){const clean=String(text||'').trim();if(!clean)return;addMessage('user',clean);addMessage('teacher','כאן תופיע תשובת המורה האמיתית אחרי חיבור ה־V2 למנוע שיעורי הבית הקיים. כרגע אני לא מייצר תשובה מדומה.');if(state.step<3)setStep(3);}
els.chatForm?.addEventListener('submit',e=>{e.preventDefault();const text=els.chatInput.value;els.chatInput.value='';submitMessage(text)});
els.quickActions?.addEventListener('click',e=>{const b=e.target.closest('button[data-message]');if(!b)return;submitMessage(b.dataset.message);if(window.innerWidth<=1000)openChat();});
els.audioPlay?.addEventListener('click',()=>{els.audioStatus.textContent='האודיו יתחבר ל־TTS הקיים';els.audioPlay.textContent='▶';});
window.IAKidsHomework={setChild(child){if(!child)return;state.child=child;if(child.name){els.childName.textContent=child.name;els.childAvatar.textContent=child.name.trim().charAt(0)||'י';}if(child.grade)els.childGrade.textContent=`כיתה ${child.grade}`;},setAnalysis(result){if(!result)return;const subject=result.subject||result.detected_subject;const topic=result.topic||result.detected_topic;els.sourceStatus.textContent=[subject,topic].filter(Boolean).join(' · ')||'הניתוח הושלם';if(subject||topic){setStep(3);els.understandingText.textContent='זיהינו את החומר';}},addTeacherMessage(text){addMessage('teacher',text)},setStep,getState(){return{step:state.step,child:state.child,file:state.file?{name:state.file.name,type:state.file.type,size:state.file.size}:null,notebook:els.notebook.innerText}}};
setStep(1);