#!/usr/bin/env python3
"""Build the nikud files the games load.

    python3 games/tools/nikud-check.py --emit > /tmp/w.txt
    python3 games/tools/nakdan.py --json /tmp/w.txt > /tmp/n.json
    python3 games/tools/nikud-build.py /tmp/n.json

Writes three kinds of file from one vocalisation:

  games/tools/nikud.full.js   every word — the master. backend/seed_nikud.py uploads
                              it and nikud-check.py checks it. No page loads it.
  games/<slug>/nikud.js       only the words that game renders, plus the SDK's own
                              labels. This is what a game loads: 1–20 KB instead of
                              the 155 KB the whole dictionary weighs.
  games/nikud.js              the same for the hub page.

The per-page word lists come from nikud-check.py's own extractor, so a page's file
holds exactly the words the checker will later demand it covers. Nothing is listed
by hand and nothing can drift.

Without /tmp/n.json it rebuilds from the existing master, which is how you re-split
after a game changes without calling Dicta again.
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # games/
sys.path.insert(0, os.path.join(ROOT, 'tools'))
MARKS = re.compile('[֑-ׇ]')

HEAD = """/* Hebrew nikud — plain word -> the same word with vowel points.
 * GENERATED by games/tools/nikud-build.py; corrections go in
 * games/tools/nikud-overrides.json, never here. {scope}
 * The letters of every value equal its key, so a game keys its logic on the
 * plain word and renders the vocalised one through IAKidsNikud. */
const IAKIDS_NIKUD = {{
"""
TAIL = "};\nif (typeof window !== 'undefined') window.IAKIDS_NIKUD = IAKIDS_NIKUD;\n"


def load_master():
    p = os.path.join(ROOT, 'tools', 'nikud.full.js')
    if not os.path.exists(p):
        p = os.path.join(ROOT, 'nikud.js')          # the pre-split location
    return dict(re.findall(r"'([א-ת]+)': '([^']+)'", open(p, encoding='utf-8').read()))


def write(path, words, scope):
    body = ''.join(f"  '{w}': '{v}',\n" for w, v in sorted(words.items()))
    with open(path, 'w', encoding='utf-8') as f:
        f.write(HEAD.format(scope=scope) + body + TAIL)
    return os.path.getsize(path)


def main():
    if len(sys.argv) > 1:
        raw = json.load(open(sys.argv[1], encoding='utf-8'))
        master = {w: v for w, v in raw.items() if v != w and MARKS.sub('', v) == w}
    else:
        master = load_master()

    # The checker's extractor is the one source of "which words does this page show".
    import importlib.util
    spec = importlib.util.spec_from_file_location('nc', os.path.join(ROOT, 'tools', 'nikud-check.py'))
    nc = importlib.util.module_from_spec(spec)
    sys.argv = [sys.argv[0]]                       # the checker reads flags from argv
    spec.loader.exec_module(nc)
    per_page = nc.hebrew_words_in_games()

    core = {w: master[w] for w in per_page.get('game-sdk', {}) if w in master}
    os.makedirs(os.path.join(ROOT, 'tools'), exist_ok=True)
    n = write(os.path.join(ROOT, 'tools', 'nikud.full.js'), master,
              'This is the master: every word, loaded by no page.')
    print(f'master  {len(master):>5} words  {n/1024:6.1f} KB  tools/nikud.full.js')

    total_before = n
    total_after = 0
    pages = 0
    for slug, counter in sorted(per_page.items()):
        if slug == 'game-sdk':
            continue
        words = {w: master[w] for w in counter if w in master}
        words.update(core)
        if slug == 'games':                       # games/index.html, the hub
            path = os.path.join(ROOT, 'nikud.js')
        else:
            d = os.path.join(ROOT, slug)
            if not os.path.isfile(os.path.join(d, 'index.html')):
                continue
            path = os.path.join(d, 'nikud.js')
        size = write(path, words, f'This file holds only what {slug} renders.')
        total_after += size
        pages += 1
    print(f'{pages} page files written; the median page now loads about '
          f'{sorted(os.path.getsize(os.path.join(ROOT, s, "nikud.js")) for s in per_page if os.path.isfile(os.path.join(ROOT, s, "nikud.js")))[pages//2]/1024:.1f} KB '
          f'instead of {total_before/1024:.0f} KB')


if __name__ == '__main__':
    main()
