#!/usr/bin/env python3
"""Load test of the tutor API, route by route, with server CPU / RSS per route.

    cd backend-ai-tutor-he
    APP_ENV=prod ../backend/.venv/bin/python tools/load_api.py --kid-id <id>                       # DB-only routes, 30 parallel × 60 requests each
    APP_ENV=prod ../backend/.venv/bin/python tools/load_api.py --kid-id <id> --concurrency 100 --requests 300
    APP_ENV=prod ../backend/.venv/bin/python tools/load_api.py --kid-id <id> --with-ai 5            # + chat and tts, 5 parallel (costs OpenAI/Gemini calls)
    APP_ENV=prod ../backend/.venv/bin/python tools/load_api.py --kid-id <id> --children 50 --seconds 60   # 50 simulated children polling like the workspace

Modes
  routes    (default) each DB-only route gets --requests requests at --concurrency parallel,
            from --tokens distinct login tokens (each token is its own rate-limit bucket, like
            distinct users). The server runs with the rate limiter lifted (RATE_LIMIT_PER_MINUTE=10^6)
            so the number measured is the server's, not the limiter's; --keep-rate-limit keeps it.
  --with-ai N   also /api/tutor/chat and /api/tutor/tts at N parallel, N requests each. Real model calls.
  --children N  N threads behave like the workspace on a freshly opened lesson: open the lesson,
            then poll audio + visuals every 1.5 s for --seconds. Rate limiter stays ON, so 429s show
            what a real child would see today.

Every mode starts its own uvicorn (+ one worker, concurrency 1) on --port, samples both every 2 s
into <logdir>/<run>/resources.csv, and prints a table per route:
  n  ok  errors{code:n}  p50  p90  max (ms)  req/s  server CPU avg/peak %  server RSS peak MB
"""
import argparse
import json
import os
import signal
import subprocess
import sys
import threading
import time
import urllib.request
import urllib.error
from collections import Counter
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
os.chdir(HERE)
sys.path.insert(0, str(HERE))

ap = argparse.ArgumentParser()
ap.add_argument("--kid-id", required=True)
ap.add_argument("--unit-lesson", type=int, default=None, help="a generated lesson with audio (auto-picked in the kid's grade)")
ap.add_argument("--concurrency", type=int, default=30)
ap.add_argument("--requests", type=int, default=60)
ap.add_argument("--tokens", type=int, default=10, help="distinct login tokens to spread requests over")
ap.add_argument("--routes", default="units,active-state,shared-transition,hero-image,visuals,audio,unit-lesson,lesson-intro")
ap.add_argument("--with-ai", type=int, default=0)
ap.add_argument("--children", type=int, default=0)
ap.add_argument("--seconds", type=int, default=60)
ap.add_argument("--keep-rate-limit", action="store_true")
ap.add_argument("--old-polling", action="store_true", help="children mode: the old fixed 1.5s polling instead of the new backoff")
ap.add_argument("--port", type=int, default=8766)
ap.add_argument("--logdir", default=os.environ.get("E2E_LOGDIR", "/var/log/iakids/load"))
args = ap.parse_args()

PY = sys.executable
RUN = time.strftime("%Y%m%d-%H%M%S")
LOGDIR = Path(args.logdir) / RUN
LOGDIR.mkdir(parents=True, exist_ok=True)
env = dict(os.environ, MEDIA_JOBS_MODE="queue", WORKER_CONCURRENCY="1", WORKER_POLL_SECONDS="2")
if not (args.keep_rate_limit or args.children):
    env["RATE_LIMIT_PER_MINUTE"] = "1000000"


def now():
    return time.strftime("%H:%M:%S")


def say(msg):
    print(f"{now()} {msg}", flush=True)


# ---------------------------------------------------------------- connect, kid, tokens
import main as tutor  # noqa: E402
from supabase import create_client  # noqa: E402

say(f"project {tutor.SUPABASE_URL} | APP_ENV={os.getenv('APP_ENV', 'dev')} | logs {LOGDIR}")
kid = tutor.sb.table("kids_profiles").select("id,user_id,child_name,age").eq("id", args.kid_id).single().execute().data
parent = tutor.sb.auth.admin.get_user_by_id(kid["user_id"]).user
say(f"kid {kid['child_name']} (age {kid['age']}) | parent {parent.email}")


def mint_token():
    link = tutor.sb.auth.admin.generate_link({"type": "magiclink", "email": parent.email})
    tmp = create_client(tutor.SUPABASE_URL, tutor.SUPABASE_SERVICE_KEY)
    return tmp.auth.verify_otp({"token_hash": link.properties.hashed_token, "type": "magiclink"}).session.access_token


TOKENS = [mint_token() for _ in range(max(1, args.tokens))]
say(f"{len(TOKENS)} login tokens minted")

# a lesson in the kid's grade that is generated and has audio (so nothing gets generated by the load)
grade = int(kid.get("age") or 0)
parents = tutor.sb.table("learning_lessons").select("id").eq("grade", grade).execute().data
parent_ids = [p["id"] for p in parents]
if args.unit_lesson:
    ul = tutor.get_unit_lesson(args.unit_lesson)
else:
    rows = (tutor.sb.table("lesson_units_content").select("id,learning_lesson_id,unit_name,lesson_name,generation_status,lesson_audio_json")
            .in_("learning_lesson_id", parent_ids).eq("generation_status", "ready").not_.is_("lesson_audio_json", "null")
            .order("id", desc=True).limit(1).execute().data)
    if not rows:
        say("no generated lesson with audio in this grade; pass --unit-lesson"); sys.exit(2)
    ul = rows[0]
say(f"lesson {ul['id']} '{ul.get('lesson_name')}' (parent {ul['learning_lesson_id']})")

# ---------------------------------------------------------------- processes + sampler
procs = {}
CLK = os.sysconf("SC_CLK_TCK")
samples = []
phase = ["startup"]
_last = {}


def _proc_stat(pid):
    try:
        with open(f"/proc/{pid}/stat") as f:
            parts = f.read().rsplit(")", 1)[1].split()
        cpu_s = (int(parts[11]) + int(parts[12])) / CLK
        with open(f"/proc/{pid}/statm") as f:
            rss = int(f.read().split()[1]) * os.sysconf("SC_PAGE_SIZE") // (1024 * 1024)
        return rss, cpu_s
    except Exception:
        return None


def _free_mb():
    with open("/proc/meminfo") as f:
        for line in f:
            if line.startswith("MemAvailable:"):
                return int(line.split()[1]) // 1024
    return -1


def sampler():
    csv = open(LOGDIR / "resources.csv", "w")
    csv.write("t,phase,server_rss_mb,server_cpu_pct,worker_rss_mb,worker_cpu_pct,mem_available_mb,load1\n")
    t0 = time.time()
    while True:
        t = time.time(); row = [round(t - t0, 1), phase[0]]
        for name in ("server", "worker"):
            p = procs.get(name); st = _proc_stat(p.pid) if p and p.poll() is None else None
            if st is None:
                row += [0, 0.0]; _last.pop(name, None); continue
            rss, cpu = st; prev = _last.get(name)
            row += [rss, 0.0 if not prev else round(100 * (cpu - prev[1]) / max(0.001, t - prev[0]), 1)]
            _last[name] = (t, cpu)
        row += [_free_mb(), round(os.getloadavg()[0], 2)]
        samples.append(tuple(row)); csv.write(",".join(map(str, row)) + "\n"); csv.flush()
        time.sleep(2)


procs["server"] = subprocess.Popen([PY, "-m", "uvicorn", "main:app", "--host", "127.0.0.1", "--port", str(args.port)],
                                   stdout=open(LOGDIR / "server.log", "ab"), stderr=subprocess.STDOUT, env=env)
procs["worker"] = subprocess.Popen([PY, "worker.py"], stdout=open(LOGDIR / "worker.log", "ab"), stderr=subprocess.STDOUT, env=env)
threading.Thread(target=sampler, daemon=True).start()
for _ in range(60):
    try:
        urllib.request.urlopen(f"http://127.0.0.1:{args.port}/", timeout=2).read(); break
    except Exception:
        time.sleep(1)
else:
    say("server never answered"); sys.exit(1)
time.sleep(2)
say(f"server up | rate limiter {'ON' if 'RATE_LIMIT_PER_MINUTE' not in env else 'lifted'} | mem available {_free_mb()} MB")


def stop_all():
    for p in procs.values():
        if p.poll() is None:
            p.send_signal(signal.SIGTERM)
    for p in procs.values():
        try:
            p.wait(timeout=30)
        except subprocess.TimeoutExpired:
            p.kill()


# ---------------------------------------------------------------- the routes
BASE = f"http://127.0.0.1:{args.port}"
ROUTES = {
    "units":             ("GET",  f"/api/learning-lessons/{ul['learning_lesson_id']}/units", None),
    "active-state":      ("POST", "/api/tutor/active-lesson-state", {"kid_id": kid["id"]}),
    "shared-transition": ("GET",  "/api/tutor/shared-transition/middle", None),
    "hero-image":        ("POST", "/api/tutor/unit-lesson/hero-image", {"kid_id": kid["id"], "unit_lesson_id": int(ul["id"])}),
    "visuals":           ("POST", "/api/tutor/unit-lesson/visuals", {"kid_id": kid["id"], "unit_lesson_id": int(ul["id"])}),
    "audio":             ("POST", "/api/tutor/unit-lesson/audio", {"kid_id": kid["id"], "unit_lesson_id": int(ul["id"])}),
    "unit-lesson":       ("POST", "/api/tutor/unit-lesson", {"kid_id": kid["id"], "unit_lesson_id": int(ul["id"])}),
    "lesson-intro":      ("POST", "/api/tutor/lesson-intro", {"kid_id": kid["id"], "unit_lesson_id": int(ul["id"])}),
    # real model calls, opt-in
    "chat":              ("POST", "/api/tutor/chat", {"kid_id": kid["id"], "message": "מה זה מערכת אקולוגית? תסביר בקצרה"}),
    "tts":               ("POST", "/api/tutor/tts", {"text": "שלום, איזה כיף שבאת ללמוד היום!"}),
}


def call(name, i):
    method, path, body = ROUTES[name]
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(BASE + path, data=data, method=method,
                                 headers={"Content-Type": "application/json", "Authorization": f"Bearer {TOKENS[i % len(TOKENS)]}"})
    t = time.time()
    try:
        with urllib.request.urlopen(req, timeout=300) as r:
            r.read(); return r.status, time.time() - t
    except urllib.error.HTTPError as e:
        e.read(); return e.code, time.time() - t
    except Exception as e:
        return 0, time.time() - t


def phase_stats(ph):
    rows = [s for s in samples if s[1] == ph]
    if not rows:
        return "-", "-", "-"
    cpu = [r[3] for r in rows]
    return f"{sum(cpu) / len(cpu):.0f}%/{max(cpu):.0f}%", f"{max(r[2] for r in rows)}MB", f"{min(r[6] for r in rows)}MB"


results = {}


def run_route(name, conc, n):
    phase[0] = name
    t0 = time.time()
    with ThreadPoolExecutor(conc) as ex:
        out = list(ex.map(lambda i: call(name, i), range(n)))
    wall = time.time() - t0
    time.sleep(2.5)                       # let the sampler see the tail of the phase
    lat = sorted(x[1] for x in out); codes = Counter(x[0] for x in out)
    ok = codes.get(200, 0); errs = {k: v for k, v in codes.items() if k != 200}
    cpu, rss, free = phase_stats(name)
    results[name] = dict(n=n, conc=conc, ok=ok, errors=errs, p50=lat[len(lat) // 2] * 1000, p90=lat[int(len(lat) * .9)] * 1000,
                         max=lat[-1] * 1000, rps=n / wall, cpu=cpu, rss=rss, free=free)
    r = results[name]
    say(f"{name:<18} n={n:<4} c={conc:<3} ok={ok:<4} err={str(errs or '-'):<14} p50={r['p50']:>7.0f}ms p90={r['p90']:>7.0f}ms max={r['max']:>7.0f}ms "
        f"{r['rps']:>6.1f} req/s | srv CPU {cpu:<10} RSS {rss:<7} free {free}")


try:
    if args.children:
        # ---- simulated children: rate limiter ON, workspace polling pattern
        phase[0] = f"children:{args.children}"
        say(f"simulating {args.children} children for {args.seconds}s: open lesson, then poll audio+visuals with {'the OLD fixed 1.5s' if args.old_polling else 'the NEW backoff (2-8s, 20s after 429)'}")
        counts = Counter(); lat = []; lock = threading.Lock()

        import random

        def poll_sleep(attempt, base_ms, status):
            """Mirror of iakidsPollSleep in he/workspace/index.html (backoff 1.5x to 8s,
            20s after a 429, 5s after a 5xx, jitter). --old-polling restores the fixed 1.5s."""
            if args.old_polling:
                return 1.5
            ms = min(8000, base_ms * (1.5 ** max(0, attempt - 1)))
            if status == 429:
                ms = max(ms, 20000)
            elif status >= 500:
                ms = max(ms, 5000)
            return (ms + random.random() * 500) / 1000

        def child(i):
            end = time.time() + args.seconds
            code, dt = call("unit-lesson", i)
            with lock:
                counts[("unit-lesson", code)] += 1; lat.append(dt)
            attempt = 0
            while time.time() < end:
                attempt += 1
                worst = 0
                for name, base in (("audio", 2000), ("visuals", 2500)):
                    code, dt = call(name, i)
                    worst = max(worst, code)
                    with lock:
                        counts[(name, code)] += 1; lat.append(dt)
                time.sleep(poll_sleep(attempt, 2000, worst))

        t0 = time.time()
        with ThreadPoolExecutor(args.children) as ex:
            list(ex.map(child, range(args.children)))
        wall = time.time() - t0; total = sum(counts.values()); lat.sort()
        cpu, rss, free = phase_stats(phase[0])
        say(f"children done: {total} requests in {wall:.0f}s = {total / wall:.1f} req/s | p50 {lat[len(lat) // 2] * 1000:.0f}ms p90 {lat[int(len(lat) * .9)] * 1000:.0f}ms | srv CPU {cpu} RSS {rss}")
        for (name, code), c in sorted(counts.items()):
            say(f"    {name:<14} HTTP {code}: {c}")
        r429 = sum(c for (n_, code), c in counts.items() if code == 429)
        say(f"    rate-limited (429): {r429} of {total}  <- what real children get with the 60/min limiter and this polling")
    else:
        names = [r.strip() for r in args.routes.split(",") if r.strip()]
        for name in names:
            run_route(name, args.concurrency, args.requests)
        if args.with_ai:
            say(f"AI routes at {args.with_ai} parallel (real OpenAI / Gemini calls)")
            for name in ("chat", "tts"):
                run_route(name, args.with_ai, args.with_ai)
        print("\nroute               n   conc  ok   errors        p50ms   p90ms   maxms   req/s  srvCPU avg/pk  RSSpk   minfree")
        for name, r in results.items():
            print(f"{name:<18} {r['n']:<5} {r['conc']:<5} {r['ok']:<4} {str(r['errors'] or '-'):<13} {r['p50']:>7.0f} {r['p90']:>7.0f} {r['max']:>7.0f} {r['rps']:>7.1f}  {r['cpu']:<13} {r['rss']:<7} {r['free']}")
        (LOGDIR / "results.json").write_text(json.dumps(results, ensure_ascii=False, indent=1))
finally:
    stop_all()
    say(f"stopped | logs {LOGDIR}")
