-- IAKIDS: per-child progress for each internal unit lesson
-- Source of truth for child/parent progress UI.

create table if not exists public.kid_unit_lesson_progress (
    id bigint generated by default as identity primary key,
    kid_id uuid not null,
    unit_lesson_id bigint not null,
    learning_lesson_id bigint not null,

    status text not null default 'not_started'
        check (status in ('not_started', 'in_progress', 'partial', 'completed')),

    progress_percent integer not null default 0
        check (progress_percent between 0 and 100),

    current_stage text,
    last_part_number integer,

    mastery_score integer not null default 0
        check (mastery_score between 0 and 100),

    best_mastery_score integer not null default 0
        check (best_mastery_score between 0 and 100),

    attempts_count integer not null default 0
        check (attempts_count >= 0),

    started_at timestamptz,
    last_activity_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint kid_unit_lesson_progress_kid_unit_unique
        unique (kid_id, unit_lesson_id),

    constraint kid_unit_lesson_progress_unit_lesson_fk
        foreign key (unit_lesson_id)
        references public.lesson_units_content(id)
        on delete cascade,

    constraint kid_unit_lesson_progress_learning_lesson_fk
        foreign key (learning_lesson_id)
        references public.learning_lessons(id)
        on delete cascade
);

create index if not exists kid_unit_lesson_progress_kid_idx
    on public.kid_unit_lesson_progress(kid_id);

create index if not exists kid_unit_lesson_progress_learning_lesson_idx
    on public.kid_unit_lesson_progress(kid_id, learning_lesson_id);

create index if not exists kid_unit_lesson_progress_status_idx
    on public.kid_unit_lesson_progress(kid_id, status);

comment on table public.kid_unit_lesson_progress is
    'Per-child source of truth for progress through lesson_units_content lessons.';

comment on column public.kid_unit_lesson_progress.status is
    'not_started, in_progress, partial, or completed. A started lesson that is left before completion becomes partial.';
