-- IAKIDS: central question bank + per-child answer history for the games.
--
-- game_questions       one row per distinct question per game (the bank).
--                      Filled by the harvester (seed) and grown at play time by
--                      game-sdk.js, which upserts every generated question.
-- kid_question_answers append-only: which child answered which question, and
--                      whether they got it right. game-sdk.js excludes a
--                      child's answered questions when picking the next one.
--
-- Both tables key on games_catalog.game_code (text) rather than games_catalog.id
-- so the bank can hold questions for games not yet registered in the catalog
-- (25 of 106 folders today) without a FK failure at insert time.

create table if not exists public.game_questions (
    id           bigint generated by default as identity primary key,
    game_code    text        not null,
    level        smallint    not null default 1 check (level between 0 and 10),
    lang         text        not null default 'he',
    qkey         text        not null,                 -- game's own identity for the question (keyFn output)
    payload      jsonb       not null,                 -- full question object as the game produced it
    answer       text,                                  -- normalised correct answer, for verification / dedupe
    source       text        not null default 'generated'
                 check (source in ('seed', 'generated', 'authored')),
    verified     boolean     not null default false,   -- set true by the verifier once answer is confirmed
    times_asked  integer     not null default 0,
    times_correct integer    not null default 0,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now(),

    constraint game_questions_game_key_unique unique (game_code, qkey)
);

create index if not exists game_questions_game_level_idx
    on public.game_questions (game_code, level);

create table if not exists public.kid_question_answers (
    id           bigint generated by default as identity primary key,
    kid_id       uuid        not null references public.kids_profiles(id) on delete cascade,
    game_code    text        not null,
    question_id  bigint      references public.game_questions(id) on delete set null,
    qkey         text        not null,                 -- kept even if the question row is deleted
    correct      boolean     not null,
    response_ms  integer,
    session_id   uuid        references public.kid_game_sessions(id) on delete set null,
    level        smallint,
    answered_at  timestamptz not null default now()
);

create index if not exists kid_question_answers_kid_game_idx
    on public.kid_question_answers (kid_id, game_code);

create index if not exists kid_question_answers_question_idx
    on public.kid_question_answers (question_id);

-- ---------------------------------------------------------------- RLS ----
alter table public.game_questions       enable row level security;
alter table public.kid_question_answers enable row level security;

-- Bank: anyone signed in can read it and add to it (the SDK grows it at play
-- time). Nobody except service_role can update or delete rows.
create policy game_questions_read
    on public.game_questions for select
    to authenticated, anon
    using (true);

-- A client insert is ALWAYS untrusted content: it arrives with the anon key, so
-- any signed-in account can post an arbitrary payload into a bank that is read
-- by every other child. Two things keep that safe:
--   1. this policy pins source/verified, so a client cannot self-promote a row
--      into the trusted set (only service_role can flip `verified`);
--   2. game_next_questions below serves ONLY trusted rows.
create policy game_questions_insert
    on public.game_questions for insert
    to authenticated
    with check (source = 'generated' and verified = false);

-- Answers: a parent account sees and writes only rows for its own children.
create policy kid_question_answers_select_own
    on public.kid_question_answers for select
    to authenticated
    using (kid_id in (select id from public.kids_profiles where user_id = auth.uid()));

create policy kid_question_answers_insert_own
    on public.kid_question_answers for insert
    to authenticated
    with check (kid_id in (select id from public.kids_profiles where user_id = auth.uid()));

-- ----------------------------------------------------------- helpers ----
-- Atomic "asked/correct" counters, called by the SDK after each answer.
-- Keyed by (game_code, qkey) so the client never needs the row id.
create or replace function public.game_question_mark(p_game text, p_key text, was_correct boolean)
returns void language sql security definer set search_path = public as $$
    update public.game_questions
       set times_asked   = times_asked + 1,
           times_correct = times_correct + (case when was_correct then 1 else 0 end),
           updated_at    = now()
     where game_code = p_game and qkey = p_key;
$$;

grant execute on function public.game_question_mark(text, text, boolean) to authenticated;

-- One round trip for the SDK: unanswered questions for this child + game + level.
--
-- TRUSTED ROWS ONLY. Rows with source='generated' were posted by a client and
-- nothing has checked them, so they are never shown to a child; they sit in the
-- bank purely as harvest for the verifier, which flips `verified` once the
-- answer is confirmed. Without this filter any signed-in account could write a
-- question that every other child would then be served.
create or replace function public.game_next_questions(
    p_kid uuid, p_game text, p_level smallint, p_limit int default 20)
returns setof public.game_questions
language sql stable security invoker set search_path = public as $$
    select q.*
      from public.game_questions q
     where q.game_code = p_game
       and (p_level = 0 or q.level = p_level)
       and (q.verified or q.source in ('seed', 'authored'))
       and not exists (select 1 from public.kid_question_answers a
                        where a.kid_id = p_kid and a.qkey = q.qkey and a.game_code = q.game_code)
     order by q.times_asked asc, random()
     limit p_limit;
$$;

grant execute on function public.game_next_questions(uuid, text, smallint, int) to authenticated;

comment on table public.game_questions is
    'Central question bank for /games. Unique per (game_code, qkey). Grown by game-sdk.js and the seed harvester.';
comment on table public.kid_question_answers is
    'Append-only history of which child answered which game question; drives no-repeat selection.';
