-- IAKIDS: Hebrew nikud dictionary — plain word -> the same word with vowel points.
--
-- The games ship the same table as a static file (games/nikud.js) and read that
-- first, so nothing here is on the critical path of a game. The table is what the
-- backends and the Hebrew tutor read, and where new words are collected as the
-- catalogue grows.
--
-- INVARIANT: stripping the marks from `nikud` gives back `word` exactly. It is
-- enforced below, so a bad row cannot be written at all.
-- Idempotent: safe to paste more than once.

create table if not exists public.hebrew_nikud (
    word        text primary key,
    nikud       text not null,
    source      text not null default 'nakdan'
        check (source in ('nakdan', 'override', 'authored')),
    -- 'override' and 'authored' rows were read by a person; 'nakdan' rows are the
    -- vocaliser's own choice and are right for the sense the games use, which for a
    -- homograph may not be the sense another caller means.
    reviewed    boolean not null default false,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

-- Letters must survive vocalisation: strip the Hebrew marks (U+0591..U+05C7) and
-- what is left has to equal the key.
alter table public.hebrew_nikud drop constraint if exists hebrew_nikud_letters_match;
alter table public.hebrew_nikud add constraint hebrew_nikud_letters_match
    check (regexp_replace(nikud, '[֑-ׇ]', '', 'g') = word);

alter table public.hebrew_nikud drop constraint if exists hebrew_nikud_word_is_hebrew;
alter table public.hebrew_nikud add constraint hebrew_nikud_word_is_hebrew
    check (word ~ '^[א-ת]{1,40}$');

create index if not exists hebrew_nikud_reviewed_idx on public.hebrew_nikud(reviewed);

alter table public.hebrew_nikud enable row level security;

-- The dictionary is public reference data: every visitor may read it, nobody may
-- write it from the browser. Writes come from backend/seed_nikud.py, which holds
-- the service-role key and bypasses RLS.
drop policy if exists hebrew_nikud_read on public.hebrew_nikud;
create policy hebrew_nikud_read
    on public.hebrew_nikud for select
    to authenticated, anon
    using (true);

comment on table public.hebrew_nikud is
    'Plain Hebrew word -> the same word with nikud (identical letters). Generated by games/tools/nakdan.py, mirrored in games/nikud.js. Read-only to clients.';
